# Generated by Django 5.2.1 on 2025-11-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_poblar_tipos_residuo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tiporesiduo',
            table='api_tipo_residuo',
        ),
    ]
